### PR TITLE
* update ArduinoJson version 5 => 6

### PR DESCRIPTION
**Pull request by fortl**
just api updates

### CODE REVIEW

**Comment by robertoostenveld** [comment]
thanks, switching from 5 to 6 was on my todo list for a long time! Did you test this on actual hardware? If so, I will merge. Right now I don't have the time to test myself.

**Comment by fortl** [comment]
Yes, I did. It works! Thank you for your work. I'm actually going to use it in my project. I'm planning to add some function such as DMX stream recording and playing, smart UI. At the next step  I want to move Serial debug to switchable macroses cause I need UART for JDY-40 radio channel. So i'll be able to make some more pull requests to your repo if you'd like)

**Comment by robertoostenveld** [comment]
Thanks: I am using very similar ESP8266 initialization and online configuration code in quite some of the other devices for which the firmware is in my "arduino" repository. I will take your changes and also port those over to my other esp8266 based devices.

Re further updates: in principle I welcome suggestions, but don't think that the current organization of my "arduino" repository works well. It is basically my whole "sketch" directory under my Arduino IDE installation, and it mixes all sorts of sketches, some documented, some not. Instead, I propose that you make a copy of the relevant code and put that in a separate repository by its own. That makes documenting easier. Also different versions of the same module could be better put side-by-side. So feel free to fork/copy and make a new project out of it. If you want, I can link from my current documentation (both here, as  well as on my website) to your new project.

Re JDY-40: out of curiosity, why did you select this specific one, and e.g. not the Nrf24L01? I did not know about the JDY-40 until now, but it looks like a nice module and 120 meters is sweet! I have mainly been using the RFM12b with other arduino boards, but its SPI interface with interrupts does not work nicely with the ESP8266.

**Comment by fortl** [comment]
Sorry for delay, just came back from my vacation!
I'm working on a project with many small portable lamps driving by DMX. I keep balance between its cost, power consumption (in waiting mode) and weight. In a single lamp I use 3.6V 1W bright LEDs , cheap ATTiny controller, so JDY-40 with UART interface, price about 0.5USD and extra-low-power is very suitable to me. It seems I can keep cost of a single lamp at about ~7-8$ with a waterproof case and reflector. ESP8266 is a Artnet to UART gate in my project. I'll definitely share my work later when it's done!

**Comment by robertoostenveld** [comment]
Interesting, also the scale tag which you seem to work. For me it is just a few controllers for small performances. Look forward to hearing more about it in the future.

**Pull request merged**
